import axios from 'axios';
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import example from './example.json';

/*
  state = {
    query
    pageNum
    movies
  }

*/

// if query, page is 1, load in movies
// if next page, query stays the same but load in next page. append new movies
// if query changes, page number is 1 again

const getMovies = async (query) => {
  console.log(query);
  // const key = process.env.REACT_APP_API_KEY;
  // const url = `https://api.themoviedb.org/3/search/movie?api_key=${key}&language=en-US&page=1&include_adult=false&query=${query}`;
  // const results = await axios.get(url);
  return example; // returning back query to store for later
}

const initialState = {
  results: [],
  status: 'idle',
  query: '',
  page: 1
};

export const getMoviesAsync = createAsyncThunk(
  'movies/getMovies',
  async (query) => {
    const response = await getMovies(query);
    // console.log(response);
    // The value we return becomes the `fulfilled` action payload
    return { response, query };
  }
);

// export const getNextPageAsync = createAsyncThunk(
//   'movies/getNextPage',
//   async (query) => {
//     const response = await getMovies(query, page);
//     // console.log(response);
//     // The value we return becomes the `fulfilled` action payload
//     return response;
//   }
// );

export const moviesSlice = createSlice({
  name: 'movies',
  initialState,
  reducers: {
    setQuery: (state, action) => {
      console.log(action.payload)
      state.query = action.payload;
    },
    clearMovieResults: (state, action) => {
      state.query = '';
      state.results = []
    }
  },
  extraReducers: (builder) => {
    builder
      .addCase(getMoviesAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getMoviesAsync.fulfilled, (state, action) => {
        const { response, query } = action.payload;
        state.status = 'idle';
        state.results = response.results;
        state.page = response.page;
        state.query = query;
      });
  },
});


// export const counterSlice = createSlice({
//   name: 'counter',
//   initialState,
//   // The `reducers` field lets us define reducers and generate associated actions
//   reducers: {
//     increment: (state) => {
//       // Redux Toolkit allows us to write "mutating" logic in reducers. It
//       // doesn't actually mutate the state because it uses the Immer library,
//       // which detects changes to a "draft state" and produces a brand new
//       // immutable state based off those changes
//       state.value += 1;
//     },
//     decrement: (state) => {
//       state.value -= 1;
//     },
//     // Use the PayloadAction type to declare the contents of `action.payload`
//     incrementByAmount: (state, action) => {
//       state.value += action.payload;
//     },
//   },
//   // The `extraReducers` field lets the slice handle actions defined elsewhere,
//   // including actions generated by createAsyncThunk or in other slices.
//   extraReducers: (builder) => {
//     builder
//       .addCase(incrementAsync.pending, (state) => {
//         state.status = 'loading';
//       })
//       .addCase(incrementAsync.fulfilled, (state, action) => {
//         state.status = 'idle';
//         state.value += action.payload;
//       });
//   },
// });
// Throttle.


export const { setQuery } = moviesSlice.actions;



// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectMovies = (state) => state.movies.results;
export const selectQuery = (state) => state.movies.query;
export const selectPage = (state) => state.movies.page;

// // We can also write thunks by hand, which may contain both sync and async logic.
// // Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default moviesSlice.reducer;
